version: "3.8"
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ${DEFAULT_VOLUME}/${APP_DATA}/nginx-proxy-manager/data:/data
      - ${DEFAULT_VOLUME}/${APP_DATA}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Nginx Proxy Manager
      - homepage.icon=nginx-proxy-manager.png
      - homepage.href=http://nginx.${DOMAIN_NAME}
      - homepage.widget.type=npm
      - homepage.widget.url=http://${IP_ADDRESS}:81
      - homepage.widget.username=${NPM_USERNAME}
      - homepage.widget.password=${DEFAULT_APP_PASSWORD}

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      # - 3000:3000/tcp
      - 2080:80/tcp
      - 2443:443/tcp
    volumes:
      - ${DEFAULT_VOLUME}/${APP_DATA}/adguardhome/work:/opt/adguardhome/work
      - ${DEFAULT_VOLUME}/${APP_DATA}/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    labels:
      - homepage.group=Adguard DNS
      - homepage.name=Primary
      - homepage.icon=azure-dns.png
      - homepage.href=http://adguard.${DOMAIN_NAME}
      - homepage.widget.type=adguard
      - homepage.widget.url=http://${IP_ADDRESS}:2080
      - homepage.widget.username=${ADGUARD_USERNAME}
      - homepage.widget.password=${DEFAULT_APP_PASSWORD}

  adguardhome-sync:
    container_name: adguardhome-sync
    image: lscr.io/linuxserver/adguardhome-sync:latest
    volumes:
      - ${DEFAULT_VOLUME}/${APP_DATA}/adguardsync:/config
    ports:
      - 8082:8080
    restart: unless-stopped
