services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      PUID: 1000
      PGID: 999
      HOMEPAGE_ALLOWED_HOSTS: ${DOMAIN_NAME}
    ports:
      - 3000:3000
    volumes:
      - ${APP_DATA}/homepage:/app/config
      - ${DEFAULT_VOLUME}:/media
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    hostname: SKULLSERVER
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA}/watchtower/config.json:/config.json
    command: scrutiny homepage nginx-proxy-manager adguardhome adguardhome-sync speedtest-tracker plex plextraktsync overseerr radarr sonarr lidarr prowlarr qbittorrent music-assistant flaresolverr watchtower
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISCORD_TOKEN}@${DISCORD_ID}"
      WATCHTOWER_SCHEDULE: "0 0 * * *" # every 12:00 AM every day
      WATCHTOWER_CLEANUP: true
      TZ: ${TZ}
    restart: unless-stopped

  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    ports:
      - "8081:80"
    environment:
      PUID: 1000
      PGID: 1000
      SPEEDTEST_SCHEDULE: 0 */2 * * *
      PRUNE_RESULTS_OLDER_THAN: 90
      TZ: ${TZ}
      APP_KEY: ${SPEEDTEST_APP_KEY}
    volumes:
      - ${APP_DATA}/speedtest-tracker/config:/config
    restart: unless-stopped
    labels:
      - homepage.group=Network
      - homepage.name=Speedtest
      - homepage.icon=librespeed.png
      - homepage.href=http://speedtest.${DOMAIN_NAME}
      - homepage.widget.type=speedtest
      - homepage.widget.url=http://${IP_ADDRESS}:8081

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8083:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ${APP_DATA}/scrutiny/config:/opt/scrutiny/config
      - ${APP_DATA}/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
    restart: unless-stopped
    labels:
      - homepage.group=Health
      - homepage.name=S.M.A.R.T Monitoring
      - homepage.icon=scrutiny.png
      - homepage.href=http://scrutiny.${DOMAIN_NAME}
      - homepage.widget.type=scrutiny
      - homepage.widget.url=http://${IP_ADDRESS}:8083

  meralco-api:
      image: ghcr.io/rairulyle/meralco-ph:latest
      container_name: meralco-ph
      ports:
        - "5000:5000"
      environment:
        TZ: ${TZ} 
      restart: unless-stopped